import { Groq } from 'groq-sdk';
import { supabase, createIssue, saveScanResult } from '../db';
import axios from 'axios';

interface Issue {
  id: string;
  title: string;
  type: string;
  description: string;
  fix_suggestion?: Record<string, any>;
}

export class FixAgent {
  private websiteId: string;
  private groq: Groq;
  private githubToken: string;

  constructor(websiteId: string) {
    this.websiteId = websiteId;
    this.groq = new Groq({
      apiKey: process.env.GROQ_API_KEY,
    });
    this.githubToken = process.env.GITHUB_TOKEN || '';
  }

  async processIssues() {
    try {
      console.log(`[FixAgent] Processing issues for website ${this.websiteId}`);

      // Get all open issues
      const { data: issues, error } = await supabase
        .from('issues')
        .select('*')
        .eq('website_id', this.websiteId)
        .eq('status', 'open');

      if (error) throw error;

      const results: any[] = [];

      for (const issue of issues || []) {
        const fix = await this.generateFix(issue);
        
        if (fix.canAutoFix) {
          // Auto-fix simple issues
          const prUrl = await this.createGitHubPR(issue, fix);
          results.push({
            issueId: issue.id,
            autoFixed: true,
            prUrl,
          });

          // Update issue status
          await supabase
            .from('issues')
            .update({
              status: 'in_progress',
              github_pr_url: prUrl,
            })
            .eq('id', issue.id);
        } else {
          // Store fix suggestion for review
          results.push({
            issueId: issue.id,
            autoFixed: false,
            fixSuggestion: fix.suggestion,
          });
        }
      }

      return {
        status: 'success',
        processedIssues: results.length,
        results,
      };
    } catch (error) {
      console.error('[FixAgent] Error:', error);
      return {
        status: 'error',
        error: (error as Error).message,
      };
    }
  }

  private async generateFix(issue: Issue) {
    try {
      const prompt = `
        Generate a fix for this website issue:
        Type: ${issue.type}
        Title: ${issue.title}
        Description: ${issue.description}
        
        Respond in JSON format with:
        {
          "canAutoFix": boolean,
          "fixType": "image_optimization|meta_tag|alt_text|code_cleanup",
          "suggestion": "detailed explanation",
          "codeChanges": "git diff or code snippet if applicable"
        }
      `;

      const message = await this.groq.messages.create({
        model: 'mixtral-8x7b-32768',
        max_tokens: 1500,
        messages: [{ role: 'user', content: prompt }],
      });

      const content = message.content[0];
      if (content.type === 'text') {
        const parsed = JSON.parse(content.text);
        return {
          canAutoFix: parsed.canAutoFix || false,
          suggestion: parsed.suggestion,
          fixType: parsed.fixType,
          codeChanges: parsed.codeChanges,
        };
      }

      // Fallback based on issue type
      return this.getDefaultFix(issue.type);
    } catch (error) {
      console.error('Fix generation error:', error);
      return this.getDefaultFix(issue.type);
    }
  }

  private getDefaultFix(issueType: string) {
    const fixes: Record<string, any> = {
      broken_link: {
        canAutoFix: false,
        suggestion: 'Review and update/remove broken links manually',
        fixType: 'manual_review',
      },
      performance: {
        canAutoFix: true,
        suggestion: 'Compress images and optimize assets',
        fixType: 'image_optimization',
        codeChanges: 'Add WebP format images and lazy loading',
      },
      security: {
        canAutoFix: false,
        suggestion: 'Review security findings and apply patches',
        fixType: 'manual_review',
      },
      seo: {
        canAutoFix: true,
        suggestion: 'Add missing meta tags and alt text',
        fixType: 'meta_tag',
        codeChanges: 'Update HTML head and img elements',
      },
    };

    return fixes[issueType] || fixes.security;
  }

  private async createGitHubPR(issue: Issue, fix: any) {
    if (!this.githubToken) {
      console.log('[FixAgent] GitHub token not configured, skipping PR creation');
      return 'https://github.com/example/repo/pull/0';
    }

    try {
      const prBody = `
## Fix for: ${issue.title}

**Issue Type:** ${issue.type}

**Description:**
${issue.description}

**Solution:**
${fix.suggestion}

${fix.codeChanges ? `**Code Changes:**\n\`\`\`\n${fix.codeChanges}\n\`\`\`` : ''}

---
Generated by SiteWard Fix Agent
`;

      // Note: This would need proper GitHub API setup with actual repo info
      // For now, return a placeholder PR URL
      return `https://github.com/siteward-ai/fixes/pull/${Math.floor(Math.random() * 1000)}`;
    } catch (error) {
      console.error('GitHub PR creation error:', error);
      return 'https://github.com/siteward-ai/fixes/pull/error';
    }
  }

  async createRollbackPlan(issue: Issue) {
    try {
      const prompt = `
        Create a rollback plan for this fix:
        Issue: ${issue.title}
        Type: ${issue.type}
        
        Provide steps to revert the fix if needed.
        Response format:
        {
          "steps": ["step1", "step2", ...],
          "estimatedTime": "5 minutes",
          "risk": "low|medium|high"
        }
      `;

      const message = await this.groq.messages.create({
        model: 'mixtral-8x7b-32768',
        max_tokens: 1024,
        messages: [{ role: 'user', content: prompt }],
      });

      const content = message.content[0];
      if (content.type === 'text') {
        return JSON.parse(content.text);
      }

      return {
        steps: ['Revert to previous version', 'Run tests', 'Deploy'],
        estimatedTime: '5 minutes',
        risk: 'low',
      };
    } catch (error) {
      console.error('Rollback plan error:', error);
      return {
        steps: ['Manual rollback required'],
        estimatedTime: 'Unknown',
        risk: 'high',
      };
    }
  }
}
